#!/bin/bash

#======================
#       SYSTEM
#======================
alias su='sudo -i'
alias sudo='sudo '
alias root='sudo -i'
alias reboot='sudo /sbin/reboot'
alias shutdown='sudo /sbin/shutdown'

alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias install='sudo apt-get install'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias l='ls -CF --color=auto --group-directories-first'
    alias la='ls -A --color=auto --group-directories-first'
    alias ll='ls -alhF --color=auto --group-directories-first'
    alias ls='ls --color=auto --group-directories-first'
    alias dir='dir --color=auto --group-directories-first'
    alias vdir='vdir --color=auto --group-directories-first'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#======================
#       DOCKER 
#======================
# alias docker-compose="docker compose"

#======================
#       PYENV
#======================
alias workon='pyenv activate'
alias deactivate='source deactivate'
alias mkvirtualenv='pyenv virtualenv'
alias rmvirtualenv='pyenv uninstall'

#======================
#         VPN 
#======================
alias wireguard_on='sudo service wg-quick@tiledb-wg start'
alias wireguard_off='sudo service wg-quick@tiledb-wg stop'

#======================
#       UTILITY
#======================
alias debug-smtp='python -m smtpd -n -c DebuggingServer localhost:1025'
alias my_ip='curl ipinfo.io/ip'
alias local_ip='hostname -I'
alias wget='wget -c'
alias untar='tar -zxvf '
alias serve='python -m SimpleHTTPServer 8000'
eval "$(thefuck --alias)"

alias ntua_vpn='sudo openvpn --config Documents/GIS_Master/ntua_vpn/ntua.ovpn --auth-user-pass Documents/GIS_Master/ntua_vpn/ntua_auth.txt'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

function snap-cleanup-function() {
#  set -eu
  snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision
    do
      snap remove "$snapname" --revision="$revision"
    done
    echo "done";
}
alias snap-cleanup='bash -c "$(declare -f snap-cleanup-function); snap-cleanup-function"'
