#!/bin/bash

# Python Virtual Env setup
export PY_VENV=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$PY_VENV
export PIP_RESPECT_VIRTUALENV=true
export POETRY_VIRTUALENVS_PATH=$HOME/.virtualenvs

# Add TileDB installation to LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/Programs/TileDB/TileDB/build/dist/lib

