#!/bin/bash

#======================
#       UTILITY
#======================
# Which shell is in use.
function which_shell() {
  if [ "$BASH_VERSION" != "" ]; then
    echo "bash"
  elif [ "$ZSH_VERSION" != "" ]; then
    echo "zsh"
  else
    echo "wtf is this shell???"
  fi
}

function last_command_status() {
  local last_status=$?
  if [ $last_status -ne 0 ]; then
    echo "%F{9}✘%f"
  else
    echo "%F{10}✔%f"
  fi
}

# Determine Connection Download/Upload Speed
function speed_test() {
  curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
}

#======================
#    PYTHON UTILITY
#======================
# Override virtual_prompt_info of virtualenv zsh plugin
function venv_info() {
  [[ -n ${VIRTUAL_ENV} ]] || return
  echo "(%F{4}${VIRTUAL_ENV:t}%f) "
}

# Create pyenv venv
# function mkvenv_pyenv(){
#   while getopts 'n:v:' opt; do
#     case $opt in
#       n) name=$OPTARG;;
#       v) version=$OPTARG;;
#       \?) echo -e "\e[31mUnknown option: -$OPTARG\e[0m" >&2; return 1;;
#     esac
#   done

#   [ -z "$name" ] && echo -e "\e[31mNew venv needs a name!\e[0m" && return 1;
#   echo "Creating VirtualEnv '$name'..."

#   if [ -z "$version" ]; then
#     echo -e "\033[33mUsing global Python version: $(python3 --version)\n\033[0m"
#     pyenv virtualenv "$(python3 --version)" "$name"
#   else
#     pyenv virtualenv "$version" "$name"
#   fi

#   return 0
# }

# Activate pyenv venv
# function workon_pyenv(){
#   pyenv activate "$1"
# }
# Deactivate pyenv venv
# function deactivate_pyenv(){
#   pyenv deactivate
# }

# Workon venv
# function venv() {
#   venv_path=$1
#   if [[ ! -d "$venv_path" ]]; then
#     venv_path=$PY_VENV/$venv_path
#   fi
#   echo "Activating venv ${venv_path}..."
#   source ${venv_path}/bin/activate
# }

# Remove Python Venv
# function venvrm() {
#   venv_path=$1
#   if [[ ! -d "$venv_path" ]]; then
#     venv_path=$PY_VENV/$venv_path
#   fi
#   echo "Removing venv ${venv_path}..."
#   source ${venv_path}/bin/activate
#   pip uninstall -y -r <(pip freeze)
#   deactivate
#   sudo rm -rf "$venv_path"
# }

#======================
#        FUNNY
#======================
function sunglasses() {
  echo -en " ( •_•)     \r"; sleep .25;
  echo -en " ( •_•)>⌐■-■\r"; sleep .25;
  echo     " (⌐■_■) seems like a $(which_shell) job...";
}
