# =======================
#        Plugins
# =======================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"

# =======================
#      Configuration
# =======================
# Enable mouse
set -g mouse on
set -g default-terminal "tmux-256color"
# True colors in terminal
set-option -sa terminal-overrides ",xterm*:Tc"

# use C-Space and C-f for the prefix.
set-option -g prefix C-Space
set-option -g prefix2 C-f
bind-key C-Space send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# set vi-mode
set-window-option -g mode-keys vi

# Continuum configuration
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '60'

set -g @tokyo-night-tmux_transparent 1

# =======================
#       keybindings
# =======================
# Open new pane in the same directory
# Alt + Shift + h = split horizontally
bind -n M-H split-window -h -c '#{pane_current_path}'
# Alt + Shift + v = split vertically
bind -n M-V split-window -v -c '#{pane_current_path}'
# Copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Synchronize panes
bind-key s set-window-option synchronize-panes\; display-message "synchronize mode toggled."

# -----------------
#    Navigation
# -----------------
# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
